//------------------------------------------------------------------------------
// <auto-generated>
//     Visual Studio regenerates this file when askai.aspx is saved.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELibraryManagement
{
    public partial class askai
    {
        protected global::System.Web.UI.WebControls.TextBox txtQuestion;
        protected global::System.Web.UI.WebControls.Button btnAsk;
        protected global::System.Web.UI.WebControls.Panel pnlAnswer;
        protected global::System.Web.UI.WebControls.Label lblAnswer;
    }
}
